name: Website Change Request
description: This form is to be used to request changes to the UGS website. Contact Mackenzie Cope mcope@utah.gov if you have any questions.
title: Page Title,  Requested change (i.e. change content, change photos, add new section, etc.)
labels: ["enhancement"]
assignees:
  - Mackenzie-Cope
body:
  - type: input
    id: webpageURL
    attributes:
        label: On what web page are you requesting a change?
        placeholder: Page Title and/or Page URL
    validations:
        required: true
  - type: textarea
    id: changedescription
    attributes:
        label: Describe the change you would like to request.
        placeholder: A clear and concise description of what you want to happen and what value it will bring. Ex. Change intro text to this "...." Feel free to attach screenshots or anything you think would help show what you're describing.
    validations:
        required: true
  - type: dropdown
    id: urgency
    attributes:
        label: How Urgent is this?
        options:
          - Low
          - Medium
          - High
    validations:
        required: true
  - type: textarea
    id: moreEvidence
    attributes:
        label: If urgent, please explain.
        placeholder: 
    validations:
        required: false
  - type: markdown
    attributes:
        value: "### **All feature requests will be reviewed for future application releases**"

